# Generated by Django 4.2.4 on 2023-08-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
